refactor: :hammer: refactor dev scripts

diff --git a/scripts/bootstrap b/scripts/bootstrap
--- a/scripts/bootstrap
+++ b/scripts/bootstrap
@@ -1,5 +1,9 @@
-#!/usr/bin/env sh
+#!/bin/sh
 . scripts/_common
+
+if ! poetry --version | grep 1.2; then
+    warn 'Poetry version 1.2 is required. This script may not function correctly.'
+fi
 
 install() {
     info 'Installing dependencies...'
@@ -12,13 +16,17 @@ psql_cmd() {
 }
 
 test_postgres() {
-    info 'Testing postgres connection...'
     psql_cmd 'select 1' >/dev/null 2>&1
-    hr
 }
 
 make_postgres() {
-    info 'Creating postgres docker container...'
+    if ! which docker; then
+        warn 'Docker not found.'
+        info 'Please either setup PostgreSQL on localhost:5432 or install Docker.'
+        exit 1
+    fi
+
+    info 'Creating PostgreSQL docker container...'
     docker run -d --rm --name postgres -e POSTGRES_HOST_AUTH_METHOD=trust -p5432:5432 postgres
     hr
 }
@@ -43,4 +51,4 @@ ensure_postgres() {
 
 install
 ensure_postgres
-scripts/migrate
+poetry run scripts/migrate
